#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/llava_onevision/modular_llava_onevision.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_llava_onevision.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# coding=utf-8
# Copyright 2024 the HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import math
from dataclasses import dataclass
from typing import Optional, Union

import numpy as np
import torch
from torch import nn

from transformers.activations import ACT2FN
from transformers.cache_utils import Cache
from transformers.generation import GenerationMixin
from transformers.image_processing_utils import select_best_resolution
from transformers.modeling_flash_attention_utils import FlashAttentionKwargs
from transformers.modeling_outputs import BaseModelOutputWithPast, ModelOutput
from transformers.modeling_utils import PreTrainedModel
from transformers.processing_utils import Unpack
from transformers.utils import TransformersKwargs, auto_docstring, can_return_tuple
from transformers.models.auto import AutoModel
from transformers.models.llava_onevision.configuration_llava_onevision import LlavaOnevisionConfig


@dataclass
@auto_docstring(
    custom_intro="""
    Llava 输出的基类，包含隐藏状态（hidden states）和注意力权重（attentions）。
    """
)
class LlavaOnevisionModelOutputWithPast(BaseModelOutputWithPast):
    r"""
    past_key_values（类型：`Cache`，可选，当传入 `use_cache=True` 或 `config.use_cache=True` 时返回）：
        这是一个 [`~cache_utils.Cache`] 实例。如需了解更多细节，请参阅我们的 [键值缓存指南](https://huggingface.co/docs/transformers/en/kv_cache)。

        该参数包含预计算的隐藏状态（即自注意力模块中的键（key）和值（value）），可用于（参考
        `past_key_values` 输入参数）提升序列解码的速度。

    image_hidden_states（类型：`torch.FloatTensor`，可选）：
        一个形状为 `(批次大小, 图片数量, 序列长度, 隐藏层维度)` 的 `torch.FloatTensor` 张量。
        由视觉编码器生成，并对最后一层隐藏状态进行投影后，得到的模型视觉隐藏状态（图片相关）。

    video_hidden_states（类型：`torch.FloatTensor`，可选）：
        一个形状为 `(批次大小 * 帧数量, 视频数量, 序列长度, 隐藏层维度)` 的 `torch.FloatTensor` 张量。
        由视觉编码器生成，并对最后一层隐藏状态进行投影后，得到的模型视觉隐藏状态（视频相关）。
    """

    image_hidden_states: Optional[torch.FloatTensor] = None
    video_hidden_states: Optional[torch.FloatTensor] = None

@dataclass
@auto_docstring(
    custom_intro="""
    LlavaOnevision 因果语言模型（或自回归语言模型）输出的基类。
    """
)
class LlavaOnevisionCausalLMOutputWithPast(ModelOutput):
    r"""
    loss（形状为 `(1,)` 的 `torch.FloatTensor` 张量，可选，仅当提供 `labels` 参数时返回）：
        语言建模损失（用于下一个token的预测任务）。
    logits（形状为 `(批次大小, 序列长度, 配置词表大小)` 的 `torch.FloatTensor` 张量）：
        语言建模头的预测得分（即经过 SoftMax 激活函数之前，词表中每个token对应的得分）。
    past_key_values（类型为 `Cache`，可选，当传入 `use_cache=True` 或 `config.use_cache=True` 时返回）：
        这是一个 [`~cache_utils.Cache`] 实例。如需了解更多细节，请参阅我们的 [键值缓存指南](https://huggingface.co/docs/transformers/en/kv_cache)。
        该参数包含预计算的隐藏状态（即自注意力模块中的键（key）和值（value）），可用于（参考
        `past_key_values` 输入参数）提升序列解码的速度。
    image_hidden_states（类型为 `torch.FloatTensor`，可选）：
        一个形状为 `(批次大小 * 图片分块数, 图片数量, 序列长度, 隐藏层维度)` 的 `torch.FloatTensor` 张量。
        由视觉编码器生成，并对最后一层隐藏状态进行投影后，得到的模型视觉隐藏状态（图片相关）。
    video_hidden_states（类型为 `torch.FloatTensor`，可选）：
        一个形状为 `(批次大小 * 视频帧数, 视频数量, 序列长度, 隐藏层维度)` 的 `torch.FloatTensor` 张量。
        由视觉编码器生成，并对最后一层隐藏状态进行投影后，得到的模型视觉隐藏状态（视频相关）。
    """

    loss: Optional[torch.FloatTensor] = None
    logits: Optional[torch.FloatTensor] = None
    past_key_values: Optional[Cache] = None
    hidden_states: Optional[tuple[torch.FloatTensor]] = None
    attentions: Optional[tuple[torch.FloatTensor]] = None
    image_hidden_states: Optional[torch.FloatTensor] = None
    video_hidden_states: Optional[torch.FloatTensor] = None


@auto_docstring
class LlavaOnevisionPreTrainedModel(PreTrainedModel):
    config: LlavaOnevisionConfig
    base_model_prefix = ""
    supports_gradient_checkpointing = True
    _no_split_modules = ["LlamaDecoderLayer"]
    _skip_keys_device_placement = "past_key_values"

    _supports_flash_attn = True
    _supports_sdpa = True

    _can_compile_fullgraph = True
    _supports_flex_attn = True
    _supports_attention_backend = True

    def _init_weights(self, module):
        std = getattr(self.config, "initializer_range", self.config.get_text_config().initializer_range)

        if isinstance(module, nn.Linear):
            module.weight.data.normal_(mean=0.0, std=std)
            if module.bias is not None:
                module.bias.data.zero_()
        elif isinstance(module, LlavaOnevisionModel):
            embed_std = 1 / math.sqrt(self.config.text_config.hidden_size)
            module.image_newline.data.normal_(mean=0.0, std=embed_std)


class LlavaOnevisionMultiModalProjector(nn.Module):
    def __init__(self, config: LlavaOnevisionConfig):
        super().__init__()
        # 我们有 hidden_size * num_feature_layers
        # hidden_size : 4096 : TextConfig.hidden_size(Qwen2-8B)
        # LallvaOnevisionConfig.vision_feature_layer : [6, 9, 11] : 3 layers

        num_feature_layers = 1 if isinstance(config.vision_feature_layer, int) else len(config.vision_feature_layer)
        self.linear_1 = nn.Linear(
            config.vision_config.hidden_size * num_feature_layers,
            config.text_config.hidden_size,
            bias=config.multimodal_projector_bias,
        )
        self.act = ACT2FN[config.projector_hidden_act]
        self.linear_2 = nn.Linear(
            config.text_config.hidden_size, config.text_config.hidden_size, bias=config.multimodal_projector_bias
        )

    def forward(self, image_features):
        hidden_states = self.linear_1(image_features)
        hidden_states = self.act(hidden_states)
        hidden_states = self.linear_2(hidden_states)
        return hidden_states


def get_anyres_image_grid_shape(image_size, grid_pinpoints, patch_size):
    """
    计算任意分辨率图像经过预处理后，生成的图像分块网格的形状。
    参数:
        image_size（元组 `tuple`）:
            输入图像的尺寸，格式为（宽度，高度）。
        grid_pinpoints（列表 `List`）:
            包含若干可选分辨率的列表。列表中的每个元素都应为一个元组或列表，
            格式为 `(高度, 宽度)`。
        patch_size（整数 `int`）:
            每个图像分块（patch）的尺寸。
    返回值:
        tuple: 图像分块网格的形状，格式为（宽度，高度）。
    """
    if not isinstance(grid_pinpoints, list):
        raise TypeError("grid_pinpoints 必须是一个包含元组或列表的列表")

    # ! 非常重要：如果 image_size 是张量（tensor）类型，必须将其转换为元组，否则会导致计算错误
    if not isinstance(image_size, (list, tuple)):
        if not isinstance(image_size, (torch.Tensor, np.ndarray)):
            raise TypeError(
                f"image_size 类型无效：{type(image_size)} 不合法，应为 list、tuple、np.ndarray 或 tensor 类型"
            )
        image_size = image_size.tolist()

    height, width = select_best_resolution(image_size, grid_pinpoints)
    return height // patch_size, width // patch_size


def image_size_to_num_patches(image_size, grid_pinpoints, patch_size: int):
    """
    计算任意分辨率图像经过预处理后，生成的图像分块（patch）总数。
    参数:
        image_size（`torch.LongTensor` / `np.ndarray` / `tuple[int, int]`）:
            输入图像的尺寸，格式为（高度，宽度）。
        grid_pinpoints（列表 `List`）:
            包含若干可选分辨率的列表。列表中的每个元素都应为一个元组或列表，
            格式为 `(高度, 宽度)`。
        patch_size（整数 `int`）:
            每个图像分块（patch）的尺寸。
    返回值:
        int: 图像分块的总数量
    """
    if not isinstance(grid_pinpoints, list):
        raise TypeError("grid_pinpoints 必须是一个包含元组或列表的列表")

    # ! 非常重要：如果 image_size 是张量（tensor）类型，必须将其转换为元组，否则会导致计算错误
    if not isinstance(image_size, (list, tuple)):
        if not isinstance(image_size, (torch.Tensor, np.ndarray)):
            raise TypeError(f"image_size 类型无效，类型：{type(image_size)}，值：{image_size}")
        image_size = image_size.tolist()

    best_resolution = select_best_resolution(image_size, grid_pinpoints)
    height, width = best_resolution
    num_patches = 0
    # 可考虑修改为：向上取整(高度/分块尺寸) * 向上取整(宽度/分块尺寸) + 1
    for i in range(0, height, patch_size):
        for j in range(0, width, patch_size):
            num_patches += 1
    # 增加基准分块（base patch）的数量
    num_patches += 1
    return num_patches

def unpad_image(tensor, original_size):
    """
    对经过填充（padding）和尺寸调整后的图像PyTorch张量，执行去填充（去除多余填充区域）操作。

    参数:
        tensor（`torch.Tensor`）:
            图像张量，默认形状为 (通道数, 高度, 宽度)。
        original_size（元组 `tuple`）:
            图像的原始尺寸，格式为（高度，宽度）。

    返回值:
        `torch.Tensor`: 去填充后的图像张量。
    """
    if not isinstance(original_size, (list, tuple)):
        if not isinstance(original_size, (torch.Tensor, np.ndarray)):
            raise TypeError(
                f"原始尺寸（original_size）类型无效：{type(original_size)} 不合法，应为 list、tuple、np.ndarray 或 tensor 类型"
            )
        original_size = original_size.tolist()

    original_height, original_width = original_size
    current_height, current_width = tensor.shape[1:]  # 跳过通道数维度，获取当前张量的高和宽

    # 计算原始图像和当前张量的宽高比
    original_aspect_ratio = original_width / original_height
    current_aspect_ratio = current_width / current_height

    if original_aspect_ratio > current_aspect_ratio:
        # 原始图像更宽：按宽度比例缩放，高度方向存在填充，去除上下填充
        scale_factor = current_width / original_width
        new_height = int(round(original_height * scale_factor, 7))
        padding = (current_height - new_height) // 2  # 计算单侧填充高度
        unpadded_tensor = tensor[:, padding : current_height - padding, :]  # 裁剪上下填充区域
    else:
        # 原始图像更高/宽高比一致：按高度比例缩放，宽度方向存在填充，去除左右填充
        scale_factor = current_height / original_height
        new_width = int(round(original_width * scale_factor, 7))
        padding = (current_width - new_width) // 2  # 计算单侧填充宽度
        unpadded_tensor = tensor[:, :, padding : current_width - padding]  # 裁剪左右填充区域

    return unpadded_tensor


@auto_docstring(
    custom_intro="""
    The Llava-Next model which consists of a vision backbone and a language model without language modeling head.
    """
)
class LlavaOnevisionModel(LlavaOnevisionPreTrainedModel):
    _checkpoint_conversion_mapping = {"language_model.model": "language_model"}

    def __init__(self, config):
        super().__init__(config)
        self.vision_tower = AutoModel.from_config(config.vision_config)

        self.multi_modal_projector = LlavaOnevisionMultiModalProjector(config)
        embed_std = 1 / math.sqrt(config.text_config.hidden_size)
        self.image_newline = nn.Parameter(torch.randn(config.text_config.hidden_size, dtype=self.dtype) * embed_std)

        self.vocab_size = config.text_config.vocab_size
        self.language_model = AutoModel.from_config(config.text_config)
        self.pad_token_id = self.config.pad_token_id if self.config.pad_token_id is not None else -1
        self.post_init()

    def get_input_embeddings(self):
        return self.language_model.get_input_embeddings()

    def set_input_embeddings(self, value):
        self.language_model.set_input_embeddings(value)

    def set_decoder(self, decoder):
        self.language_model = decoder

    def get_decoder(self):
        return self.language_model

    def pack_image_features(self, image_features, image_sizes, image_newline=None, vision_aspect_ratio="anyres_max_9"):
        """
        Reshape, unpad and then pack each image_feature into a single image_features tensor containing all visual vectors.

        Args:
            image_features (`list[torch.Tensor]` of length num_images, each of shape `(num_patches, image_length, embed_dim)`)
                List of image feature tensor, each contains all the visual feature of all patches.
            image_sizes (`torch.Tensor` of shape `(num_images, 2)`)
                Actual image size of each images (H, W).
            image_newline (`torch.Tensor` of shape `(embed_dim)`)
                New line embedding vector.
            vision_aspect_ratio (`str`, *optional*, "anyres_max_9"):
                Aspect ratio used when processong image features. The default value is "anyres_max_9".
        Returns:
            image_features (`torch.Tensor` of shape `(all_feat_len, embed_dim)`)
            feature_lens (`list[int]`)
                token length of each image in image_features
        """
        new_image_features = []
        feature_lens = []
        for image_idx, image_feature in enumerate(image_features):
            if image_feature.shape[0] > 1:
                base_image_feature = image_feature[0]
                image_feature = image_feature[1:]
                height = width = self.config.vision_config.image_size // self.config.vision_config.patch_size
                if height * width != base_image_feature.shape[0]:
                    raise ValueError("The number of patches is not consistent with the image size.")
                num_patch_height, num_patch_width = get_anyres_image_grid_shape(
                    image_sizes[image_idx],
                    self.config.image_grid_pinpoints,
                    self.config.vision_config.image_size,
                )
                image_feature = image_feature.view(num_patch_height, num_patch_width, height, width, -1)
                image_feature = image_feature.permute(4, 0, 2, 1, 3).contiguous()
                image_feature = image_feature.flatten(1, 2).flatten(2, 3)
                image_feature = unpad_image(image_feature, image_sizes[image_idx])
                max_num_patches = int(vision_aspect_ratio.strip("anyres_max_"))
                channels, curr_height, curr_width = image_feature.shape
                ratio = math.sqrt(curr_height * curr_width / (max_num_patches * height**2))
                if ratio > 1.1:
                    image_feature = image_feature[None]
                    image_feature = nn.functional.interpolate(
                        image_feature, [int(curr_height // ratio), int(curr_width // ratio)], mode="bilinear"
                    )[0]
                if image_newline is not None:
                    image_feature = torch.cat(
                        (
                            image_feature,
                            image_newline[:, None, None]
                            .expand(*image_feature.shape[:-1], 1)
                            .to(image_feature.device, image_feature.dtype),
                        ),
                        dim=-1,
                    )
                image_feature = image_feature.flatten(1, 2).transpose(0, 1)
                image_feature = torch.cat((base_image_feature, image_feature), dim=0)
            else:
                image_feature = image_feature[0]
                if image_newline is not None:
                    image_feature = torch.cat((image_feature, image_newline[None].to(image_feature)), dim=0)
            new_image_features.append(image_feature)
            feature_lens.append(image_feature.size(0))
        feature_lens = torch.tensor(feature_lens, dtype=torch.long, device=image_features[0].device)
        return new_image_features, feature_lens

    def get_image_features(
        self,
        pixel_values: torch.FloatTensor,
        image_sizes: torch.Tensor,
        vision_feature_layer: Optional[Union[int, list[int]]] = None,
        vision_feature_select_strategy: Optional[str] = None,
        vision_aspect_ratio: Optional[str] = None,
        batch_num_images: Optional[torch.LongTensor] = None,
    ):
        """
        Obtains image last hidden states from the vision tower and apply multimodal projection.

        Args:
            pixel_values (`torch.FloatTensor]` of shape `(batch_size, num_patches, channels, height, width)`)
               The tensors corresponding to the input images.
            image_sizes (`torch.Tensor` of shape `(num_images, 2)`)
                Actual image size of each images (H, W).
            vision_feature_layer (`Union[int, list[int]]`):
                The index of the layer to select the vision feature. If multiple indices are provided,
                the vision feature of the corresponding indices will be concatenated to form the
                vision features.
            vision_feature_select_strategy (`str`):
                The feature selection strategy used to select the vision feature from the vision backbone.
                Can be one of `"default"` or `"full"`
            batch_num_images (`torch.LongTensor`, *optional*):
                Number of images in each sample.
        Returns:
            image_features (list[`torch.Tensor`]): List of image feature tensor, each contains all the visual feature of all patches
            and are of shape `(num_patches, image_length, embed_dim)`).
        """
        vision_feature_layer = (
            vision_feature_layer if vision_feature_layer is not None else self.config.vision_feature_layer
        )
        vision_feature_select_strategy = (
            vision_feature_select_strategy
            if vision_feature_select_strategy is not None
            else self.config.vision_feature_select_strategy
        )
        vision_aspect_ratio = (
            vision_aspect_ratio if vision_aspect_ratio is not None else self.config.vision_aspect_ratio
        )

        # ! infer image_num_patches from image_sizes
        if batch_num_images is None:
            # treat this as a single-image case for backward compatibility
            need_patching = [True] * len(image_sizes)
        else:
            need_patching = [n == 1 for n in batch_num_images for _ in range(n)]
        image_num_patches = [
            image_size_to_num_patches(
                image_size=imsize,
                grid_pinpoints=self.config.image_grid_pinpoints,
                patch_size=self.config.vision_config.image_size,
            )
            if should_patch
            else 1
            for imsize, should_patch in zip(image_sizes, need_patching)
        ]
        if pixel_values.dim() == 5:
            # stacked if input is (batch_size, num_patches, num_channels, height, width)
            _pixel_values_list = [pix_val[:num_patch] for pix_val, num_patch in zip(pixel_values, image_num_patches)]
            pixel_values = torch.cat(_pixel_values_list, dim=0)
        elif pixel_values.dim() != 4:
            # otherwise has to be stacked from list of (num_patches, num_channels, height, width)
            raise ValueError(f"pixel_values of shape {pixel_values.shape}, expect to be of 4 or 5 dimensions")

        image_features = self.vision_tower(pixel_values, output_hidden_states=True)
        # If we have one vision feature layer, return the corresponding hidden states,
        # otherwise, select the hidden states of each feature layer and concatenate them
        if isinstance(vision_feature_layer, int):
            selected_image_feature = image_features.hidden_states[vision_feature_layer]
        else:
            hs_pool = [image_features.hidden_states[layer_idx] for layer_idx in vision_feature_layer]
            selected_image_feature = torch.cat(hs_pool, dim=-1)

        if vision_feature_select_strategy == "default":
            selected_image_feature = selected_image_feature[:, 1:]
        image_features = self.multi_modal_projector(selected_image_feature)
        image_features = torch.split(image_features, image_num_patches, dim=0)

        image_features, feature_lens = self.pack_image_features(
            image_features,
            image_sizes,
            image_newline=self.image_newline,
            vision_aspect_ratio=vision_aspect_ratio,
        )
        return image_features

    def get_placeholder_mask(
        self,
        input_ids: torch.LongTensor,
        inputs_embeds: torch.FloatTensor,
        image_features: Optional[torch.FloatTensor] = None,
        video_features: Optional[torch.FloatTensor] = None,
    ):
        """
        Obtains multimodal placeholder mask from `input_ids` or `inputs_embeds`, and checks that the placeholder token count is
        equal to the length of multimodal features. If the lengths are different, an error is raised.
        """
        if input_ids is None:
            special_image_mask = inputs_embeds == self.get_input_embeddings()(
                torch.tensor(self.config.image_token_id, dtype=torch.long, device=inputs_embeds.device)
            )
            special_image_mask = special_image_mask.all(-1)
            special_video_mask = inputs_embeds == self.get_input_embeddings()(
                torch.tensor(self.config.video_token_id, dtype=torch.long, device=inputs_embeds.device)
            )
            special_video_mask = special_video_mask.all(-1)
        else:
            special_image_mask = input_ids == self.config.image_token_id
            special_video_mask = input_ids == self.config.video_token_id

        n_image_tokens = special_image_mask.sum()
        special_image_mask = special_image_mask.unsqueeze(-1).expand_as(inputs_embeds).to(inputs_embeds.device)
        if image_features is not None and inputs_embeds[special_image_mask].numel() != image_features.numel():
            raise ValueError(
                f"Image features and image tokens do not match: tokens: {n_image_tokens}, features {image_features.shape[0]}"
            )

        n_video_tokens = special_video_mask.sum()
        special_video_mask = special_video_mask.unsqueeze(-1).expand_as(inputs_embeds).to(inputs_embeds.device)
        if video_features is not None and inputs_embeds[special_video_mask].numel() != video_features.numel():
            raise ValueError(
                f"Videos features and image tokens do not match: tokens: {n_video_tokens}, features {video_features.shape[0]}"
            )

        return special_image_mask, special_video_mask

    @can_return_tuple
    @auto_docstring
    def forward(
        self,
        input_ids: Optional[torch.LongTensor] = None,
        pixel_values: Optional[torch.FloatTensor] = None,
        image_sizes: Optional[torch.LongTensor] = None,
        pixel_values_videos: Optional[torch.FloatTensor] = None,
        image_sizes_videos: Optional[torch.LongTensor] = None,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Cache] = None,
        inputs_embeds: Optional[torch.FloatTensor] = None,
        vision_feature_layer: Optional[Union[int, list[int]]] = None,
        vision_feature_select_strategy: Optional[str] = None,
        vision_aspect_ratio: Optional[str] = None,
        batch_num_images: Optional[torch.LongTensor] = None,
        use_cache: Optional[bool] = None,
        output_attentions: Optional[bool] = None,
        output_hidden_states: Optional[bool] = None,
        return_dict: Optional[bool] = None,
        cache_position: Optional[torch.LongTensor] = None,
        **kwargs: Unpack[FlashAttentionKwargs],
    ) -> Union[tuple, LlavaOnevisionModelOutputWithPast]:
        r"""
        image_sizes_videos (`torch.LongTensor` of shape `(batch_size, frames, 2)`, *optional*):
            The sizes of the videos in the batch, being (height, width) for each frame in the video.
        vision_aspect_ratio (`str`, *optional*, defaults to `"anyres_max_9"`):
            Aspect ratio used when processong image features. The default value is "anyres_max_9".
        batch_num_images (`torch.LongTensor`, *optional*):
            Number of images in each sample.
        """

        output_attentions = output_attentions if output_attentions is not None else self.config.output_attentions
        output_hidden_states = (
            output_hidden_states if output_hidden_states is not None else self.config.output_hidden_states
        )
        return_dict = return_dict if return_dict is not None else self.config.use_return_dict
        vision_feature_layer = (
            vision_feature_layer if vision_feature_layer is not None else self.config.vision_feature_layer
        )
        vision_feature_select_strategy = (
            vision_feature_select_strategy
            if vision_feature_select_strategy is not None
            else self.config.vision_feature_select_strategy
        )
        vision_aspect_ratio = (
            vision_aspect_ratio if vision_aspect_ratio is not None else self.config.vision_aspect_ratio
        )

        if (input_ids is None) ^ (inputs_embeds is not None):
            raise ValueError("You must specify exactly one of input_ids or inputs_embeds")

        if inputs_embeds is None:
            inputs_embeds = self.get_input_embeddings()(input_ids)

        # Images are processed with Anyres
        if pixel_values is not None:
            image_features = self.get_image_features(
                pixel_values,
                image_sizes,
                vision_feature_layer=vision_feature_layer,
                vision_feature_select_strategy=vision_feature_select_strategy,
                batch_num_images=batch_num_images,
            )
            image_features = torch.cat(image_features, dim=0)
            image_features = image_features.to(inputs_embeds.device, inputs_embeds.dtype)
            special_image_mask, _ = self.get_placeholder_mask(
                input_ids, inputs_embeds=inputs_embeds, image_features=image_features
            )
            inputs_embeds = inputs_embeds.masked_scatter(special_image_mask, image_features)

        # Video are simply embedded and further pooled to decrease seq len
        if pixel_values_videos is not None:
            video_features = self.get_video_features(
                pixel_values_videos,
                vision_feature_layer=vision_feature_layer,
                vision_feature_select_strategy=vision_feature_select_strategy,
            )
            image_newline = (
                self.image_newline[None, None, :].repeat(video_features.shape[0], 1, 1).to(video_features.device)
            )
            video_features = torch.cat((video_features, image_newline), dim=1)
            video_features = video_features.flatten(0, 1).to(inputs_embeds.device, inputs_embeds.dtype)
            _, special_video_mask = self.get_placeholder_mask(
                input_ids, inputs_embeds=inputs_embeds, video_features=video_features
            )
            inputs_embeds = inputs_embeds.masked_scatter(special_video_mask, video_features)

        outputs = self.language_model(
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_values=past_key_values,
            inputs_embeds=inputs_embeds,
            use_cache=use_cache,
            output_attentions=output_attentions,
            output_hidden_states=output_hidden_states,
            return_dict=True,
            cache_position=cache_position,
            **kwargs,
        )

        return LlavaOnevisionModelOutputWithPast(
            last_hidden_state=outputs.last_hidden_state,
            past_key_values=outputs.past_key_values,
            hidden_states=outputs.hidden_states,
            attentions=outputs.attentions,
            image_hidden_states=image_features if pixel_values is not None else None,
            video_hidden_states=video_features if pixel_values_videos is not None else None,
        )

    def get_video_features(
        self,
        pixel_values: torch.FloatTensor,
        vision_feature_layer: Union[int, list[int]],
        vision_feature_select_strategy: str,
    ):
        """
        Obtains video last hidden states from the vision tower, apply multimodal projection and pooling.

        Args:
            pixel_values (`torch.FloatTensor]` of shape `(batch_size, num_frames, channels, height, width)`)
               The tensors corresponding to the input video.
            vision_feature_layer (`Union[int, list[int]], *optional*, defaults to -2`):
                The index of the layer to select the vision feature. If multiple indices are provided,
                the vision feature of the corresponding indices will be concatenated to form the
                vision features.
            vision_feature_select_strategy (`str`):
                The feature selection strategy used to select the vision feature from the vision backbone.
                Can be one of `"default"` or `"full"`
        Returns:
            video_features (list[`torch.Tensor`]): List of video feature tensor, each contains all the visual feature of all patches
            and are of shape `(num_videos, video_length, embed_dim)`).
        """
        batch_size, frames, channels, height, width = pixel_values.shape
        pixel_values = pixel_values.view(batch_size * frames, channels, height, width)
        video_features = self.vision_tower(pixel_values, output_hidden_states=True)

        # If we have one vision feature layer, return the corresponding hidden states,
        # otherwise, select the hidden states of each feature layer and concatenate them
        if isinstance(vision_feature_layer, int):
            selected_video_feature = video_features.hidden_states[vision_feature_layer]
        else:
            hs_pool = [video_features.hidden_states[layer_idx] for layer_idx in vision_feature_layer]
            selected_video_feature = torch.cat(hs_pool, dim=-1)

        if vision_feature_select_strategy == "default":
            selected_video_feature = selected_video_feature[:, 1:]
        video_features = self.multi_modal_projector(selected_video_feature)

        video_features = self.apply_pooling(video_features)
        video_features = video_features.reshape(batch_size, frames * video_features.shape[1], -1)

        return video_features

    def apply_pooling(self, image_features):
        height = width = self.config.vision_config.image_size // self.config.vision_config.patch_size
        batch_frames, seq_len, dim = image_features.shape
        image_features = image_features.view(batch_frames, height, width, -1)
        image_features = image_features.permute(0, 3, 1, 2).contiguous()

        height, width = image_features.shape[2:]
        scaled_shape = [math.ceil(height / 2), math.ceil(width / 2)]
        image_features = nn.functional.interpolate(image_features, size=scaled_shape, mode="bilinear")

        image_features = image_features.permute(0, 2, 3, 1)
        image_features = image_features.view(batch_frames, -1, dim)
        return image_features


@auto_docstring(
    custom_intro="""
    Llava-Next 模型，由视觉骨干网络（vision backbone）和不含语言建模头（language modeling head）的语言模型组成。
    """
)
class LlavaOnevisionModel(LlavaOnevisionPreTrainedModel):
    # 检查点转换映射：将旧键名映射到新键名，用于模型权重加载兼容
    _checkpoint_conversion_mapping = {"language_model.model": "language_model"}

    def __init__(self, config):
        super().__init__(config)
        # 初始化视觉骨干网络（基于视觉配置构建）
        self.vision_tower = AutoModel.from_config(config.vision_config)

        # 初始化多模态投影层（实现视觉特征与语言特征的维度对齐）
        self.multi_modal_projector = LlavaOnevisionMultiModalProjector(config)
        # 计算嵌入标准差，用于初始化图像换行嵌入参数
        embed_std = 1 / math.sqrt(config.text_config.hidden_size)
        # 初始化图像换行嵌入（可学习参数，用于图文特征融合时的格式补充）
        self.image_newline = nn.Parameter(torch.randn(config.text_config.hidden_size, dtype=self.dtype) * embed_std)

        # 记录词表大小、初始化语言模型
        self.vocab_size = config.text_config.vocab_size
        self.language_model = AutoModel.from_config(config.text_config)
        # 设置PAD token id（填充标记），无配置时默认-1
        self.pad_token_id = self.config.pad_token_id if self.config.pad_token_id is not None else -1
        # 模型初始化后处理（如权重初始化等）
        self.post_init()

    def get_input_embeddings(self):
        """获取语言模型的输入嵌入层"""
        return self.language_model.get_input_embeddings()

    def set_input_embeddings(self, value):
        """设置语言模型的输入嵌入层"""
        self.language_model.set_input_embeddings(value)

    def set_decoder(self, decoder):
        """设置语言模型的解码器"""
        self.language_model = decoder

    def get_decoder(self):
        """获取语言模型的解码器"""
        return self.language_model

    def pack_image_features(self, image_features, image_sizes, image_newline=None, vision_aspect_ratio="anyres_max_9"):
        """
        对图像特征进行重塑、去填充，然后将每张图像的特征打包为单个包含所有视觉向量的图像特征张量。

        参数:
            image_features（长度为图像数量的`list[torch.Tensor]`，每个张量形状为 `(分块数量, 图像序列长度, 嵌入维度)`）:
                图像特征张量列表，每个张量包含单张图像所有分块的全部视觉特征。
            image_sizes（形状为 `(图像数量, 2)` 的`torch.Tensor`）:
                每张图像的实际尺寸（高度，宽度）。
            image_newline（形状为 `(嵌入维度)` 的`torch.Tensor`）:
                换行嵌入向量，用于图文特征融合时补充格式信息。
            vision_aspect_ratio（字符串，可选，默认值为"anyres_max_9"）:
                处理图像特征时使用的宽高比策略，默认值为"anyres_max_9"。

        返回值:
            image_features（形状为 `(所有特征长度, 嵌入维度)` 的`torch.Tensor`）:
                打包后的合并图像特征张量。
            feature_lens（`list[int]`）:
                每张图像在合并特征张量中对应的token长度。
        """
        new_image_features = []
        feature_lens = []
        # 遍历每张图像的特征
        for image_idx, image_feature in enumerate(image_features):
            if image_feature.shape[0] > 1:
                # 分离基础图像特征与其他分块特征
                base_image_feature = image_feature[0]
                image_feature = image_feature[1:]
                # 计算视觉模型默认的分块高宽（由图像尺寸和分块尺寸推导）
                height = width = self.config.vision_config.image_size // self.config.vision_config.patch_size
                # 校验基础特征的分块数量与默认尺寸是否一致
                if height * width != base_image_feature.shape[0]:
                    raise ValueError("分块数量与图像尺寸不一致。")
                # 计算任意分辨率下的图像分块网格形状
                num_patch_height, num_patch_width = get_anyres_image_grid_shape(
                    image_sizes[image_idx],
                    self.config.image_grid_pinpoints,
                    self.config.vision_config.image_size,
                )
                # 重塑图像特征形状并调整维度顺序
                image_feature = image_feature.view(num_patch_height, num_patch_width, height, width, -1)
                image_feature = image_feature.permute(4, 0, 2, 1, 3).contiguous()
                image_feature = image_feature.flatten(1, 2).flatten(2, 3)
                # 对图像特征执行去填充操作，去除多余填充区域
                image_feature = unpad_image(image_feature, image_sizes[image_idx])
                # 获取最大分块数量（从宽高比策略字符串中提取）
                max_num_patches = int(vision_aspect_ratio.strip("anyres_max_"))
                channels, curr_height, curr_width = image_feature.shape
                # 计算缩放比例，用于限制分块数量不超过最大值
                ratio = math.sqrt(curr_height * curr_width / (max_num_patches * height**2))
                if ratio > 1.1:
                    # 若比例超过阈值，对图像特征进行下采样
                    image_feature = image_feature[None]
                    image_feature = nn.functional.interpolate(
                        image_feature, [int(curr_height // ratio), int(curr_width // ratio)], mode="bilinear"
                    )[0]
                # 若提供了换行嵌入，将其拼接至图像特征后
                if image_newline is not None:
                    image_feature = torch.cat(
                        (
                            image_feature,
                            image_newline[:, None, None]
                            .expand(*image_feature.shape[:-1], 1)
                            .to(image_feature.device, image_feature.dtype),
                        ),
                        dim=-1,
                    )
                # 展平特征并调整维度顺序，再与基础图像特征拼接
                image_feature = image_feature.flatten(1, 2).transpose(0, 1)
                image_feature = torch.cat((base_image_feature, image_feature), dim=0)
            else:
                # 若图像特征只有1个分块，直接提取并拼接换行嵌入（如有）
                image_feature = image_feature[0]
                if image_newline is not None:
                    image_feature = torch.cat((image_feature, image_newline[None].to(image_feature)), dim=0)
            # 收集处理后的图像特征和对应长度
            new_image_features.append(image_feature)
            feature_lens.append(image_feature.size(0))
        # 将长度列表转换为张量格式
        feature_lens = torch.tensor(feature_lens, dtype=torch.long, device=image_features[0].device)
        return new_image_features, feature_lens

    def get_image_features(
        self,
        pixel_values: torch.FloatTensor,
        image_sizes: torch.Tensor,
        vision_feature_layer: Optional[Union[int, list[int]]] = None,
        vision_feature_select_strategy: Optional[str] = None,
        vision_aspect_ratio: Optional[str] = None,
        batch_num_images: Optional[torch.LongTensor] = None,
    ):
        """
        从视觉骨干网络中获取图像的最后一层隐藏状态，并应用多模态投影层进行维度映射。

        参数:
            pixel_values（形状为 `(批次大小, 分块数量, 通道数, 高度, 宽度)` 的`torch.FloatTensor`）:
                对应输入图像的张量。
            image_sizes（形状为 `(图像数量, 2)` 的`torch.Tensor`）:
                每张图像的实际尺寸（高度，宽度）。
            vision_feature_layer（`Union[int, list[int]]`）:
                用于提取视觉特征的网络层索引。若提供多个索引，对应层的视觉特征将被拼接后返回。
            vision_feature_select_strategy（字符串）:
                从视觉骨干网络中选择视觉特征的策略，可选值为 `"default"` 或 `"full"`。
            batch_num_images（`torch.LongTensor`，可选）:
                批次中每个样本包含的图像数量。

        返回值:
            image_features（`list[torch.Tensor]`）:
                图像特征张量列表，每个张量包含单张图像所有分块的全部视觉特征，形状为 `(分块数量, 图像序列长度, 嵌入维度)`。
        """
        # 若未指定参数，使用模型配置中的默认值
        vision_feature_layer = (
            vision_feature_layer if vision_feature_layer is not None else self.config.vision_feature_layer
        )
        vision_feature_select_strategy = (
            vision_feature_select_strategy
            if vision_feature_select_strategy is not None
            else self.config.vision_feature_select_strategy
        )
        vision_aspect_ratio = (
            vision_aspect_ratio if vision_aspect_ratio is not None else self.config.vision_aspect_ratio
        )

        # 从图像尺寸推断每张图像的分块数量
        if batch_num_images is None:
            # 兼容旧版本，默认按单图像场景处理
            need_patching = [True] * len(image_sizes)
        else:
            # 标记是否需要进行分块处理（仅单图像样本需要）
            need_patching = [n == 1 for n in batch_num_images for _ in range(n)]
        # 计算每张图像的分块数量
        image_num_patches = [
            image_size_to_num_patches(
                image_size=imsize,
                grid_pinpoints=self.config.image_grid_pinpoints,
                patch_size=self.config.vision_config.image_size,
            )
            if should_patch
            else 1
            for imsize, should_patch in zip(image_sizes, need_patching)
        ]
        # 处理像素值张量，确保格式正确
        if pixel_values.dim() == 5:
            # 若输入为5维张量，按分块数量拆分后拼接
            _pixel_values_list = [pix_val[:num_patch] for pix_val, num_patch in zip(pixel_values, image_num_patches)]
            pixel_values = torch.cat(_pixel_values_list, dim=0)
        elif pixel_values.dim() != 4:
            # 输入张量维度必须为4或5，否则抛出异常
            raise ValueError(f"pixel_values 形状为 {pixel_values.shape}，预期为4或5维张量")

        # 从视觉骨干网络中提取图像特征（输出所有隐藏状态）
        image_features = self.vision_tower(pixel_values, output_hidden_states=True)
        # 选择指定层的视觉特征（单一层索引直接提取，多层索引拼接后返回）
        if isinstance(vision_feature_layer, int):
            selected_image_feature = image_features.hidden_states[vision_feature_layer]
        else:
            hs_pool = [image_features.hidden_states[layer_idx] for layer_idx in vision_feature_layer]
            selected_image_feature = torch.cat(hs_pool, dim=-1)

        # 根据特征选择策略处理视觉特征（default策略去除第一个token）
        if vision_feature_select_strategy == "default":
            selected_image_feature = selected_image_feature[:, 1:]
        # 应用多模态投影层，将视觉特征映射到语言模型维度
        image_features = self.multi_modal_projector(selected_image_feature)
        # 按图像分块数量拆分特征张量
        image_features = torch.split(image_features, image_num_patches, dim=0)

        # 对图像特征进行打包处理
        image_features, feature_lens = self.pack_image_features(
            image_features,
            image_sizes,
            image_newline=self.image_newline,
            vision_aspect_ratio=vision_aspect_ratio,
        )
        return image_features

    def get_placeholder_mask(
        self,
        input_ids: torch.LongTensor,
        inputs_embeds: torch.FloatTensor,
        image_features: Optional[torch.FloatTensor] = None,
        video_features: Optional[torch.FloatTensor] = None,
    ):
        """
        从`input_ids`或`inputs_embeds`中获取多模态占位符掩码，并校验占位符token数量与多模态特征长度是否一致。
        若长度不一致，将抛出异常。
        """
        if input_ids is None:
            # 若未提供input_ids，从inputs_embeds中生成图像/视频占位符掩码
            special_image_mask = inputs_embeds == self.get_input_embeddings()(
                torch.tensor(self.config.image_token_id, dtype=torch.long, device=inputs_embeds.device)
            )
            special_image_mask = special_image_mask.all(-1)
            special_video_mask = inputs_embeds == self.get_input_embeddings()(
                torch.tensor(self.config.video_token_id, dtype=torch.long, device=inputs_embeds.device)
            )
            special_video_mask = special_video_mask.all(-1)
        else:
            # 若提供input_ids，直接通过token id生成掩码
            special_image_mask = input_ids == self.config.image_token_id
            special_video_mask = input_ids == self.config.video_token_id

        # 统计图像占位符token数量，并扩展掩码维度以匹配输入嵌入
        n_image_tokens = special_image_mask.sum()
        special_image_mask = special_image_mask.unsqueeze(-1).expand_as(inputs_embeds).to(inputs_embeds.device)
        # 校验图像特征与占位符token数量是否匹配
        if image_features is not None and inputs_embeds[special_image_mask].numel() != image_features.numel():
            raise ValueError(
                f"图像特征与图像token数量不匹配：token数量 {n_image_tokens}，特征数量 {image_features.shape[0]}"
            )

        # 统计视频占位符token数量，并扩展掩码维度以匹配输入嵌入
        n_video_tokens = special_video_mask.sum()
        special_video_mask = special_video_mask.unsqueeze(-1).expand_as(inputs_embeds).to(inputs_embeds.device)
        # 校验视频特征与占位符token数量是否匹配
        if video_features is not None and inputs_embeds[special_video_mask].numel() != video_features.numel():
            raise ValueError(
                f"视频特征与视频token数量不匹配：token数量 {n_video_tokens}，特征数量 {video_features.shape[0]}"
            )

        return special_image_mask, special_video_mask

    @can_return_tuple
    @auto_docstring
    def forward(
        self,
        input_ids: Optional[torch.LongTensor] = None,
        pixel_values: Optional[torch.FloatTensor] = None,
        image_sizes: Optional[torch.LongTensor] = None,
        pixel_values_videos: Optional[torch.FloatTensor] = None,
        image_sizes_videos: Optional[torch.LongTensor] = None,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Cache] = None,
        inputs_embeds: Optional[torch.FloatTensor] = None,
        vision_feature_layer: Optional[Union[int, list[int]]] = None,
        vision_feature_select_strategy: Optional[str] = None,
        vision_aspect_ratio: Optional[str] = None,
        batch_num_images: Optional[torch.LongTensor] = None,
        use_cache: Optional[bool] = None,
        output_attentions: Optional[bool] = None,
        output_hidden_states: Optional[bool] = None,
        return_dict: Optional[bool] = None,
        cache_position: Optional[torch.LongTensor] = None,
        **kwargs: Unpack[FlashAttentionKwargs],
    ) -> Union[tuple, LlavaOnevisionModelOutputWithPast]:
        r"""
        image_sizes_videos（形状为 `(批次大小, 帧数, 2)` 的`torch.LongTensor`，可选）:
            批次中视频的尺寸，其中每个视频帧的尺寸格式为（高度，宽度）。
        vision_aspect_ratio（字符串，可选，默认值为"anyres_max_9"）:
            处理图像特征时使用的宽高比策略，默认值为"anyres_max_9"。
        batch_num_images（`torch.LongTensor`，可选）:
            批次中每个样本包含的图像数量。
        """
        # 初始化默认参数（优先使用传入值，无传入值时使用模型配置）
        output_attentions = output_attentions if output_attentions is not None else self.config.output_attentions
        output_hidden_states = (
            output_hidden_states if output_hidden_states is not None else self.config.output_hidden_states
        )
        return_dict = return_dict if return_dict is not None else self.config.use_return_dict
        vision_feature_layer = (
            vision_feature_layer if vision_feature_layer is not None else self.config.vision_feature_layer
        )
        vision_feature_select_strategy = (
            vision_feature_select_strategy
            if vision_feature_select_strategy is not None
            else self.config.vision_feature_select_strategy
        )
        vision_aspect_ratio = (
            vision_aspect_ratio if vision_aspect_ratio is not None else self.config.vision_aspect_ratio
        )

        # 校验input_ids和inputs_embeds是否互斥（必须且只能指定一个）
        if (input_ids is None) ^ (inputs_embeds is not None):
            raise ValueError("必须且只能指定 input_ids 或 inputs_embeds 中的一个")

        # 若未提供inputs_embeds，从input_ids生成输入嵌入
        if inputs_embeds is None:
            inputs_embeds = self.get_input_embeddings()(input_ids)

        # 处理图像特征：提取并替换输入嵌入中的图像占位符
        if pixel_values is not None:
            image_features = self.get_image_features(
                pixel_values,
                image_sizes,
                vision_feature_layer=vision_feature_layer,
                vision_feature_select_strategy=vision_feature_select_strategy,
                batch_num_images=batch_num_images,
            )
            # 拼接所有图像特征并转换为与输入嵌入一致的设备和数据类型
            image_features = torch.cat(image_features, dim=0)
            image_features = image_features.to(inputs_embeds.device, inputs_embeds.dtype)
            # 获取图像占位符掩码
            special_image_mask, _ = self.get_placeholder_mask(
                input_ids, inputs_embeds=inputs_embeds, image_features=image_features
            )
            # 用图像特征替换输入嵌入中的图像占位符
            inputs_embeds = inputs_embeds.masked_scatter(special_image_mask, image_features)

        # 处理视频特征：提取、拼接换行嵌入并替换输入嵌入中的视频占位符
        if pixel_values_videos is not None:
            video_features = self.get_video_features(
                pixel_values_videos,
                vision_feature_layer=vision_feature_layer,
                vision_feature_select_strategy=vision_feature_select_strategy,
            )
            # 生成视频对应的换行嵌入并拼接至视频特征后
            image_newline = (
                self.image_newline[None, None, :].repeat(video_features.shape[0], 1, 1).to(video_features.device)
            )
            video_features = torch.cat((video_features, image_newline), dim=1)
            # 展平视频特征并转换为与输入嵌入一致的设备和数据类型
            video_features = video_features.flatten(0, 1).to(inputs_embeds.device, inputs_embeds.dtype)
            # 获取视频占位符掩码
            _, special_video_mask = self.get_placeholder_mask(
                input_ids, inputs_embeds=inputs_embeds, video_features=video_features
            )
            # 用视频特征替换输入嵌入中的视频占位符
            inputs_embeds = inputs_embeds.masked_scatter(special_video_mask, video_features)

        # 将融合后的输入嵌入传入语言模型进行前向传播
        outputs = self.language_model(
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_values=past_key_values,
            inputs_embeds=inputs_embeds,
            use_cache=use_cache,
            output_attentions=output_attentions,
            output_hidden_states=output_hidden_states,
            return_dict=True,
            cache_position=cache_position,
            **kwargs,
        )

        # 返回模型输出（封装为LlavaOnevisionModelOutputWithPast格式）
        return LlavaOnevisionModelOutputWithPast(
            last_hidden_state=outputs.last_hidden_state,
            past_key_values=outputs.past_key_values,
            hidden_states=outputs.hidden_states,
            attentions=outputs.attentions,
            image_hidden_states=image_features if pixel_values is not None else None,
            video_hidden_states=video_features if pixel_values_videos is not None else None,
        )

    def get_video_features(
        self,
        pixel_values: torch.FloatTensor,
        vision_feature_layer: Union[int, list[int]],
        vision_feature_select_strategy: str,
    ):
        """
        从视觉骨干网络中获取视频的最后一层隐藏状态，应用多模态投影层并执行池化操作以降低序列长度。

        参数:
            pixel_values（形状为 `(批次大小, 帧数, 通道数, 高度, 宽度)` 的`torch.FloatTensor`）:
                对应输入视频的张量。
            vision_feature_layer（`Union[int, list[int]]`，可选，默认值为-2）:
                用于提取视觉特征的网络层索引。若提供多个索引，对应层的视觉特征将被拼接后返回。
            vision_feature_select_strategy（字符串）:
                从视觉骨干网络中选择视觉特征的策略，可选值为 `"default"` 或 `"full"`。

        返回值:
            video_features（`list[torch.Tensor]`）:
                视频特征张量列表，每个张量包含单个视频所有分块的全部视觉特征，形状为 `(视频数量, 视频序列长度, 嵌入维度)`。
        """
        # 获取视频张量的维度信息并重塑为2维（批次*帧数, 通道数, 高度, 宽度）
        batch_size, frames, channels, height, width = pixel_values.shape
        pixel_values = pixel_values.view(batch_size * frames, channels, height, width)
        # 从视觉骨干网络中提取视频特征（输出所有隐藏状态）
        video_features = self.vision_tower(pixel_values, output_hidden_states=True)

        # 选择指定层的视频特征（单一层索引直接提取，多层索引拼接后返回）
        if isinstance(vision_feature_layer, int):
            selected_video_feature = video_features.hidden_states[vision_feature_layer]
        else:
            hs_pool = [video_features.hidden_states[layer_idx] for layer_idx in vision_feature_layer]
            selected_video_feature = torch.cat(hs_pool, dim=-1)

        # 根据特征选择策略处理视频特征（default策略去除第一个token）
        if vision_feature_select_strategy == "default":
            selected_video_feature = selected_video_feature[:, 1:]
        # 应用多模态投影层，将视频特征映射到语言模型维度
        video_features = self.multi_modal_projector(selected_video_feature)

        # 对视频特征执行池化操作，降低序列长度
        video_features = self.apply_pooling(video_features)
        # 重塑视频特征形状为（批次大小, 帧数*池化后序列长度, 嵌入维度）
        video_features = video_features.reshape(batch_size, frames * video_features.shape[1], -1)

        return video_features

    def apply_pooling(self, image_features):
        """对视觉特征执行双线性插值池化操作，降低序列长度"""
        # 计算视觉模型默认的分块高宽
        height = width = self.config.vision_config.image_size // self.config.vision_config.patch_size
        batch_frames, seq_len, dim = image_features.shape
        # 重塑特征形状并调整维度顺序
        image_features = image_features.view(batch_frames, height, width, -1)
        image_features = image_features.permute(0, 3, 1, 2).contiguous()

        # 计算池化后的目标尺寸（宽高各减半，向上取整）
        height, width = image_features.shape[2:]
        scaled_shape = [math.ceil(height / 2), math.ceil(width / 2)]
        # 应用双线性插值进行下采样
        image_features = nn.functional.interpolate(image_features, size=scaled_shape, mode="bilinear")

        # 调整维度顺序并重塑为原始特征格式
        image_features = image_features.permute(0, 2, 3, 1)
        image_features = image_features.view(batch_frames, -1, dim)
        return image_features

__all__ = ["LlavaOnevisionModel", "LlavaOnevisionForConditionalGeneration", "LlavaOnevisionPreTrainedModel"]
